"""vessel model

Revision ID: 903db4b04dbb
Revises: 
Create Date: 2020-06-08 22:06:04.997158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903db4b04dbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessel')
    # ### end Alembic commands ###
